# Generated by Django 2.0.3 on 2018-03-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
